### ISSUE TITLE
Blaze http client doesn't support proxy settings

### ISSUE THREAD

**Issue by elyast** [http4s/blaze#14]
I tried to set commonly used http.httpHost ... however without luck, it does seem looking at the code its missing feature.

As an example I am getting such exception:
```
Exception in thread "main" java.net.ConnectException: Operation timed out
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:301)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bryce-anderson** [comment]
You're correct, as of current, blaze has no notion of a proxy. I don't know what ```http.httpHost``` is: what package does it live in? Is it ```org.apache.http.HttpHost``` in the apache HttpCore library?

**Comment by elyast** [comment]
Sorry I meant system properties like -Dhttp.proxyHost=x.x.x.x -Dhttp.proxyPort=x

They are usually respected by other http clients

**Comment by bryce-anderson** [comment]
Are you using blaze directly, or using it through ```http4s```?

**Comment by elyast** [comment]
I believe I was using http4s blaze-client package

**Comment by elyast** [comment]
I'd like to help making this happen, where do u think I should start?

**Comment by bryce-anderson** [comment]
First things first, lets move this to the http4s repo instead of the blaze repo. 

I'm not practiced in the art of http proxy, so if any of the below procedure is wrong, let me know. I've never implemented it, just done a little reading (prompted by your issue).

1. We need to add the ability to configure a proxy [here](https://github.com/http4s/http4s/blob/master/blaze-client/src/main/scala/org/http4s/client/blaze/SimpleHttp1Client.scala) and [here](https://github.com/http4s/http4s/blob/master/blaze-client/src/main/scala/org/http4s/client/blaze/PooledHttp1Client.scala).
2. Next, we need the clients (pooled and simple) to know to rewrite the request line to include the whole url. This will need to be done in [Http1ClientStage](https://github.com/http4s/http4s/blob/master/blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala#L137). That means it also needs to know about the proxy (if there is one). It gets initialized from [Http1Support](https://github.com/http4s/http4s/blob/master/blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala) which means you must pass the proxy config down the line.

Could you also please link some appropriate RFC's/whatever else you find relevant in the issue?

I haven't though much about how https will effect all of this, and probably should read about it. At any rate, do you want to close this issue, open an appropriate one in http4s/http4s? Please copy the discourse above and reference this issue when you do. I'm happy to help guide you through the process, but know I'm not an expert in proxy so I hope to learn something in the process as well.
